name: BeerIsMyChurch
favicon: null
layout_spectrum: 0.6918922618497163
typography_spectrum: 0.7594259874895215
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9772276212461293
  lightness: 0.9277256594505161
  saturation: 0.48387597408145666
  rhythmicContrast: 0.04185569495894015
purpose: []
